# Generated by Django 3.0.5 on 2020-04-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='products/'),
            preserve_default=False,
        ),
    ]
